packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@storybook/react': ^8.6.14
  '@storybook/react-vite': ^8.6.14
  '@tanstack/react-query': ^5.90.12
  '@tanstack/react-query-devtools': ^5.91.1
  '@types/node': ^24.9.2
  '@types/react': ^19.2.3
  '@types/react-dom': ^19.2.3
  '@vitest/coverage-istanbul': ^4.0.18
  ai: ^6.0.58
  date-fns: ^4.1.0
  msw: ^2.12.4
  react: ^19.2.3
  react-dom: ^19.2.3
  react-router: ^7.13.0
  typescript: ^5.9.3
  uuid: ^11.0.3
  vite: ^7.1.12
  vitest: ^4.0.18
  zod: ^4.0.0

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
