packages:
  - apps/*
  - packages/**
  - tooling/*

catalog:
  '@tanstack/react-query': 5.90.12
  '@tanstack/react-query-devtools': 5.91.1
  '@types/node': 24.9.2
  '@types/react': 19.2.3
  '@types/react-dom': 19.2.3
  '@vitest/coverage-istanbul': '^4.0.18'
  'react': '19.2.3'
  'react-dom': '19.2.3'
  'react-router': '^7.13.0'
  'zod': '^3.25.76'
  'vitest': '^4.0.18'
  'vite': '^7.1.12'
  'typescript': '^5.9.3'
  'msw': '^2.12.4'
  'uuid': '^11.0.3'
  'date-fns': '^4.1.0'
  'ai': '^6.0.58'
  '@storybook/react': '^8.6.14'
  '@storybook/react-vite': '^8.6.14'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@sentry/cli'
  - better-sqlite3
