// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/version": {
    params: {};
  };
  "/healthcheck": {
    params: {};
  };
  "/qwery/*": {
    params: {
      "*": string;
    };
  };
  "/api/init": {
    params: {};
  };
  "/api/driver/command": {
    params: {};
  };
  "/api/extensions/registry": {
    params: {};
  };
  "/api/notebook/prompt": {
    params: {};
  };
  "/api/notebook/query": {
    params: {};
  };
  "/organizations": {
    params: {};
  };
  "/org/:slug": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug": {
    params: {
      "slug": string;
    };
  };
  "/notebook/:slug": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/notebooks": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/ds": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/ds/new": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/ds/:id/new": {
    params: {
      "slug": string;
      "id": string;
    };
  };
  "/prj/:slug/playground": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/c": {
    params: {
      "slug": string;
    };
  };
  "/c/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ds/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ds/:slug/tables": {
    params: {
      "slug": string;
    };
  };
  "/ds/:slug/tables/:id": {
    params: {
      "slug": string;
      "id": string;
    };
  };
  "/ds/:slug/schema": {
    params: {
      "slug": string;
    };
  };
  "/ds/:slug/settings": {
    params: {
      "slug": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/version" | "/healthcheck" | "/qwery/*" | "/api/init" | "/api/driver/command" | "/api/extensions/registry" | "/api/notebook/prompt" | "/api/notebook/query" | "/organizations" | "/org/:slug" | "/prj/:slug" | "/notebook/:slug" | "/prj/:slug/notebooks" | "/prj/:slug/ds" | "/prj/:slug/ds/new" | "/prj/:slug/ds/:id/new" | "/prj/:slug/playground" | "/prj/:slug/c" | "/c/:slug" | "/ds/:slug" | "/ds/:slug/tables" | "/ds/:slug/tables/:id" | "/ds/:slug/schema" | "/ds/:slug/settings" | "/*";
  };
  "routes/version.ts": {
    id: "routes/version";
    page: "/version";
  };
  "routes/healthcheck.ts": {
    id: "routes/healthcheck";
    page: "/healthcheck";
  };
  "routes/ingest.$.ts": {
    id: "routes/ingest.$";
    page: "/qwery/*";
  };
  "routes/api/init.ts": {
    id: "routes/api/init";
    page: "/api/init";
  };
  "routes/api/driver/command.ts": {
    id: "routes/api/driver/command";
    page: "/api/driver/command";
  };
  "routes/api/extensions/registry.ts": {
    id: "routes/api/extensions/registry";
    page: "/api/extensions/registry";
  };
  "routes/api/notebook/prompt.ts": {
    id: "routes/api/notebook/prompt";
    page: "/api/notebook/prompt";
  };
  "routes/api/notebook/query.ts": {
    id: "routes/api/notebook/query";
    page: "/api/notebook/query";
  };
  "routes/layout/layout.tsx": {
    id: "routes/layout/layout";
    page: "/";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/organizations/layout.tsx": {
    id: "routes/organizations/layout";
    page: "/organizations";
  };
  "routes/organizations/index.tsx": {
    id: "routes/organizations/index";
    page: "/organizations";
  };
  "routes/organization/layout.tsx": {
    id: "routes/organization/layout";
    page: "/org/:slug";
  };
  "routes/organization/index.tsx": {
    id: "routes/organization/index";
    page: "/org/:slug";
  };
  "routes/project/layout.tsx": {
    id: "routes/project/layout";
    page: "/prj/:slug" | "/notebook/:slug" | "/prj/:slug/notebooks" | "/prj/:slug/ds" | "/prj/:slug/ds/new" | "/prj/:slug/ds/:id/new" | "/prj/:slug/playground" | "/prj/:slug/c" | "/c/:slug";
  };
  "routes/project/index.tsx": {
    id: "routes/project/index";
    page: "/prj/:slug";
  };
  "routes/project/notebook.tsx": {
    id: "routes/project/notebook";
    page: "/notebook/:slug";
  };
  "routes/project/notebooks/index.tsx": {
    id: "routes/project/notebooks/index";
    page: "/prj/:slug/notebooks";
  };
  "routes/project/datasources/index.tsx": {
    id: "routes/project/datasources/index";
    page: "/prj/:slug/ds";
  };
  "routes/project/datasources/sources.tsx": {
    id: "routes/project/datasources/sources";
    page: "/prj/:slug/ds/new";
  };
  "routes/project/datasources/new.tsx": {
    id: "routes/project/datasources/new";
    page: "/prj/:slug/ds/:id/new";
  };
  "routes/project/playground.tsx": {
    id: "routes/project/playground";
    page: "/prj/:slug/playground";
  };
  "routes/project/conversation/index.tsx": {
    id: "routes/project/conversation/index";
    page: "/prj/:slug/c";
  };
  "routes/project/conversation/conversation.tsx": {
    id: "routes/project/conversation/conversation";
    page: "/c/:slug";
  };
  "routes/datasource/layout.tsx": {
    id: "routes/datasource/layout";
    page: "/ds/:slug" | "/ds/:slug/tables" | "/ds/:slug/tables/:id" | "/ds/:slug/schema" | "/ds/:slug/settings";
  };
  "routes/datasource/index.tsx": {
    id: "routes/datasource/index";
    page: "/ds/:slug";
  };
  "routes/datasource/tables.tsx": {
    id: "routes/datasource/tables";
    page: "/ds/:slug/tables";
  };
  "routes/datasource/table.tsx": {
    id: "routes/datasource/table";
    page: "/ds/:slug/tables/:id";
  };
  "routes/datasource/schema.tsx": {
    id: "routes/datasource/schema";
    page: "/ds/:slug/schema";
  };
  "routes/datasource/settings.tsx": {
    id: "routes/datasource/settings";
    page: "/ds/:slug/settings";
  };
  "routes/404.tsx": {
    id: "routes/404";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/version": typeof import("./app/routes/version.ts");
  "routes/healthcheck": typeof import("./app/routes/healthcheck.ts");
  "routes/ingest.$": typeof import("./app/routes/ingest.$.ts");
  "routes/api/init": typeof import("./app/routes/api/init.ts");
  "routes/api/driver/command": typeof import("./app/routes/api/driver/command.ts");
  "routes/api/extensions/registry": typeof import("./app/routes/api/extensions/registry.ts");
  "routes/api/notebook/prompt": typeof import("./app/routes/api/notebook/prompt.ts");
  "routes/api/notebook/query": typeof import("./app/routes/api/notebook/query.ts");
  "routes/layout/layout": typeof import("./app/routes/layout/layout.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/organizations/layout": typeof import("./app/routes/organizations/layout.tsx");
  "routes/organizations/index": typeof import("./app/routes/organizations/index.tsx");
  "routes/organization/layout": typeof import("./app/routes/organization/layout.tsx");
  "routes/organization/index": typeof import("./app/routes/organization/index.tsx");
  "routes/project/layout": typeof import("./app/routes/project/layout.tsx");
  "routes/project/index": typeof import("./app/routes/project/index.tsx");
  "routes/project/notebook": typeof import("./app/routes/project/notebook.tsx");
  "routes/project/notebooks/index": typeof import("./app/routes/project/notebooks/index.tsx");
  "routes/project/datasources/index": typeof import("./app/routes/project/datasources/index.tsx");
  "routes/project/datasources/sources": typeof import("./app/routes/project/datasources/sources.tsx");
  "routes/project/datasources/new": typeof import("./app/routes/project/datasources/new.tsx");
  "routes/project/playground": typeof import("./app/routes/project/playground.tsx");
  "routes/project/conversation/index": typeof import("./app/routes/project/conversation/index.tsx");
  "routes/project/conversation/conversation": typeof import("./app/routes/project/conversation/conversation.tsx");
  "routes/datasource/layout": typeof import("./app/routes/datasource/layout.tsx");
  "routes/datasource/index": typeof import("./app/routes/datasource/index.tsx");
  "routes/datasource/tables": typeof import("./app/routes/datasource/tables.tsx");
  "routes/datasource/table": typeof import("./app/routes/datasource/table.tsx");
  "routes/datasource/schema": typeof import("./app/routes/datasource/schema.tsx");
  "routes/datasource/settings": typeof import("./app/routes/datasource/settings.tsx");
  "routes/404": typeof import("./app/routes/404.tsx");
};